# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Xilinx/project/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_40_158_sada_level7/bram_40_158_sada_level7.xci
# IP: The module: 'bram_40_158_sada_level7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx/project/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_40_158_sada_level7/bram_40_158_sada_level7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_40_158_sada_level7'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: e:/Xilinx/project/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_40_158_sada_level7/bram_40_158_sada_level7.xci
# IP: The module: 'bram_40_158_sada_level7' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx/project/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_40_158_sada_level7/bram_40_158_sada_level7_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_40_158_sada_level7'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
