# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Xilinx/project/IPC_10k_test/IPC_10k_test.srcs/sources_1/ip/bram_40_512_sada_level4/bram_40_512_sada_level4.xci
# IP: The module: 'bram_40_512_sada_level4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx/project/IPC_10k_test/IPC_10k_test.srcs/sources_1/ip/bram_40_512_sada_level4/bram_40_512_sada_level4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_40_512_sada_level4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: E:/Xilinx/project/IPC_10k_test/IPC_10k_test.srcs/sources_1/ip/bram_40_512_sada_level4/bram_40_512_sada_level4.xci
# IP: The module: 'bram_40_512_sada_level4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Xilinx/project/IPC_10k_test/IPC_10k_test.srcs/sources_1/ip/bram_40_512_sada_level4/bram_40_512_sada_level4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_40_512_sada_level4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
