@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Oct 16 19:06:38 +0800 2021
REM SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim testbench_sa_behav -key {Behavioral:sim_1:Functional:testbench_sa} -tclbatch testbench_sa.tcl -view E:/Xilinx/project/IPC_10k_test/testbench_sa_behav1.wcfg -log simulate.log"
call xsim  testbench_sa_behav -key {Behavioral:sim_1:Functional:testbench_sa} -tclbatch testbench_sa.tcl -view E:/Xilinx/project/IPC_10k_test/testbench_sa_behav1.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
