# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/MBitTree.xdc

# IP: ip/bram_40_64_sada_level3/bram_40_64_sada_level3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_40_64_sada_level3 || ORIG_REF_NAME==bram_40_64_sada_level3} -quiet] -quiet

# IP: ip/bram_40_64_da_level5/bram_40_64_da_level5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_40_64_da_level5 || ORIG_REF_NAME==bram_40_64_da_level5} -quiet] -quiet

# IP: ip/bram_40_8_sada_level2/bram_40_8_sada_level2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bram_40_8_sada_level2 || ORIG_REF_NAME==bram_40_8_sada_level2} -quiet] -quiet
