# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.runs/synth_2/MBitTree.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_2" START { ROLLUP_AUTO }
set_msg_config  -id {[Synth 8-5858]}  -new_severity {INFO} 
set_msg_config  -id {Common 17-55}  -string {{ERROR: [Common 17-55] 'set_property' expects at least one object.
Resolution: If [get_<value>] was used to populate the object, check to make sure this command returns at least one valid object.}}  -suppress 
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7vx690tffg1761-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.cache/wt [current_project]
set_property parent.project_path G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo g:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_171_sa/sa_rule_bucket.coe
add_files G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_40_512/sa_level4.coe
add_files G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_40_64_sa_level3/sa_level3.coe
add_files G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_40_64/sa_level2.coe
add_files G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/sa_level5.coe
add_files G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/dram_40_16_sa_level2.coe
add_files G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_40_8_sa_level2.coe
read_verilog -library xil_defaultlib {
  G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/new/MBitTree.v
  G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/new/prioritySolver.v
  G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/new/Reg_match_priority.v
  G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/new/Reg_level2_lelvel3.v
  G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/new/Reg_level3_level4.v
  G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/new/Reg_root_level2.v
  G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/new/reg_multi_pipeline.v
  G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/new/final_prio_solver.v
  G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/new/ruleMatch_SADA.v
  G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/new/ruleMatch_DA.v
  G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/new/pipeline_SADA.v
  G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/new/pipeline_DA.v
  G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/new/Reg_tree_rulematch.v
  G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/new/TreeLevel4_SADA.v
  G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/new/TreeLevel4_DA.v
  G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/new/TreeLevel3_SADA.v
  G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/new/root_SADA.v
  G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/new/TreeLevel2_SADA.v
  G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/new/TreeLevel3_DA.v
  G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/new/root_DA.v
  G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/new/TreeLevel2_DA.v
  G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/new/TreeLevel5_DA.v
  G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/new/TreeLevel6_SADA.v
  G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/new/Reg_level5_level6.v
  G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/new/TreeLevel6_DA.v
  G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/new/TreeLevel5_SADA.v
  G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/new/Reg_level4_level5.v
}
read_ip -quiet G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_40_64_sada_level3/bram_40_64_sada_level3.xci
set_property used_in_implementation false [get_files -all g:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_40_64_sada_level3/bram_40_64_sada_level3_ooc.xdc]

read_ip -quiet G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_40_64_da_level5/bram_40_64_da_level5.xci
set_property used_in_implementation false [get_files -all g:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_40_64_da_level5/bram_40_64_da_level5_ooc.xdc]

read_ip -quiet G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_40_8_sada_level2/bram_40_8_sada_level2.xci
set_property used_in_implementation false [get_files -all g:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_40_8_sada_level2/bram_40_8_sada_level2_ooc.xdc]

read_ip -quiet G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_171_da/bram_171_da.xci
set_property used_in_implementation false [get_files -all g:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_171_da/bram_171_da_ooc.xdc]

read_ip -quiet G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_171_sada/bram_171_sada.xci
set_property used_in_implementation false [get_files -all g:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_171_sada/bram_171_sada_ooc.xdc]

read_ip -quiet G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_40_512_da_level4/bram_40_512_da_level4.xci
set_property used_in_implementation false [get_files -all g:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_40_512_da_level4/bram_40_512_da_level4_ooc.xdc]

read_ip -quiet G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_40_64_da_level3/bram_40_64_da_level3.xci
set_property used_in_implementation false [get_files -all g:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_40_64_da_level3/bram_40_64_da_level3_ooc.xdc]

read_ip -quiet G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_40_512_sada_level4/bram_40_512_sada_level4.xci
set_property used_in_implementation false [get_files -all g:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_40_512_sada_level4/bram_40_512_sada_level4_ooc.xdc]

read_ip -quiet G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_40_8_da_level2/bram_40_8_da_level2.xci
set_property used_in_implementation false [get_files -all g:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_40_8_da_level2/bram_40_8_da_level2_ooc.xdc]

read_ip -quiet G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_40_1914_sada_level5/bram_40_1914_sada_level5.xci
set_property used_in_implementation false [get_files -all g:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_40_1914_sada_level5/bram_40_1914_sada_level5_ooc.xdc]

read_ip -quiet G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_40_998_sada_level6/bram_40_998_sada_level6.xci
set_property used_in_implementation false [get_files -all g:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_40_998_sada_level6/bram_40_998_sada_level6_ooc.xdc]

read_ip -quiet G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_40_158_sada_level7/bram_40_158_sada_level7.xci
set_property used_in_implementation false [get_files -all g:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/sources_1/ip/bram_40_158_sada_level7/bram_40_158_sada_level7_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/constrs_1/new/MBitTree.xdc
set_property used_in_implementation false [get_files G:/code/DecisionTree_ACL_10K/DecisionTree_ACL_10K.srcs/constrs_1/new/MBitTree.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top MBitTree -part xc7vx690tffg1761-2 -directive PerformanceOptimized -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5
OPTRACE "synth_design" END { }


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MBitTree.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_2_synth_report_utilization_0" "report_utilization -file MBitTree_utilization_synth.rpt -pb MBitTree_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_2" END { }
